LeaveReportApp/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LeaveReportApp.Data;
using LeaveReportApp.Models;

namespace LeaveReportApp.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly LeaveReportDbContext _context;

        public EmployeesController(LeaveReportDbContext context)
        {
            _context = context;
        }

        // GET: Employees
        public async Task<IActionResult> Index()
        {
            return View(await _context.Employees.ToListAsync());
        }

        // GET: Employees/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                
                .FirstOrDefaultAsync(m => m.EmpId == id);


            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // GET: Employees/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EmpId,FirstName,LastName,Roles")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                _context.Add(employee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }

        // GET: Employees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees.FindAsync(id);
            if (employee == null)
            {
                return NotFound();
            }
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EmpId,FirstName,LastName,Roles")] Employee employee)
        {
            if (id != employee.EmpId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(employee);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeeExists(employee.EmpId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }

        // GET: Employees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.EmpId == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var employee = await _context.Employees.FindAsync(id);
            if (employee != null)
            {
                _context.Employees.Remove(employee);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmployeeExists(int id)
        {
            return _context.Employees.Any(e => e.EmpId == id);
        }
    }
}

LeaveReportApp/Controllers/LeaveReportsController.cs
using LeaveReportApp.Data;
using LeaveReportApp.Data.Enum;
using LeaveReportApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace LeaveReportApp.Controllers
{
    public class LeaveReportsController : Controller
    {
        private readonly LeaveReportDbContext _context;

        public LeaveReportsController(LeaveReportDbContext context)
        {
            _context = context;
        }

        // GET: LeaveReports
        public async Task<IActionResult> Index(string searchString, LeaveType type, int? selectedMonth)
        {

            if (_context.LeaveReports == null)
            {
                return Problem("Entity set 'LeaveReportsApp.LeaveReport'  is null.");
            }

            IQueryable<LeaveType> reportQuery = from l in _context.LeaveReports
                                                orderby l.LeaveType
                                                select l.LeaveType;

            var lR = from l in _context.LeaveReports
                     .Include(e => e.Employee)
                     select l;


            if (!String.IsNullOrEmpty(searchString)) //filter leave reports by search string (first names)
            {
                lR = lR.Where(s => s.Employee!.FirstName.Contains(searchString));
            }
            if (type != null && type != 0) // filter leave reports by leave type, if not selected all types are shown
            {
                lR = lR.Where(x => x.LeaveType == type);
            }
            if (selectedMonth.HasValue && selectedMonth != 0) // filter leave reports by which month it was created
            {
                lR = lR.Where(x => x.LeaveReportDate.Month == selectedMonth.Value);
            }

            var monthsList = Enum.GetValues(typeof(Months)).Cast<Months>().Select(m => new SelectListItem //creates list of months to select from
            {
                Text = m.ToString(),
                Value = ((int)m).ToString()
            });

            var leaveTypeReportVM = new LeaveTypeReportViewModel
            {
                LeaveTypes = new SelectList(await reportQuery.Distinct().ToListAsync()),
                LeaveReports = await lR.ToListAsync(),
                Months = new SelectList(monthsList, "Value", "Text", selectedMonth)
            };

            return View(leaveTypeReportVM);
        }


        // GET: LeaveReports/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leaveReport = await _context.LeaveReports
                .Include(l => l.Employee)
                .FirstOrDefaultAsync(m => m.LeaveReportId == id);

            if (leaveReport == null)
            {
                return NotFound();
            }

            return View(leaveReport);
        }

        // GET: LeaveReports/Create
        public IActionResult Create()
        {
            ViewData["FkEmployeeId"] = new SelectList(_context.Employees, "EmpId", "FirstName");
            return View();
        }

        // POST: LeaveReports/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LeaveReportId,StartDate,EndDate,LeaveReportDate,LeaveType,FkEmployeeId")] LeaveReport leaveReport)
        {
            if (ModelState.IsValid)
            {
                _context.Add(leaveReport);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FkEmployeeId"] = new SelectList(_context.Employees, "EmpId", "FirstName", leaveReport.FkEmployeeId);
            return View(leaveReport);
        }

        // GET: LeaveReports/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leaveReport = await _context.LeaveReports.FindAsync(id);
            if (leaveReport == null)
            {
                return NotFound();
            }
            ViewData["FkEmployeeId"] = new SelectList(_context.Employees, "EmpId", "FirstName", leaveReport.FkEmployeeId);
            return View(leaveReport);
        }

        // POST: LeaveReports/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LeaveReportId,StartDate,EndDate,LeaveReportDate,LeaveType,FkEmployeeId")] LeaveReport leaveReport)
        {
            if (id != leaveReport.LeaveReportId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(leaveReport);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LeaveReportExists(leaveReport.LeaveReportId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FkEmployeeId"] = new SelectList(_context.Employees, "EmpId", "FirstName", leaveReport.FkEmployeeId);
            return View(leaveReport);
        }

        // GET: LeaveReports/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leaveReport = await _context.LeaveReports
                .Include(l => l.Employee)
                .FirstOrDefaultAsync(m => m.LeaveReportId == id);
            if (leaveReport == null)
            {
                return NotFound();
            }

            return View(leaveReport);
        }

        // POST: LeaveReports/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var leaveReport = await _context.LeaveReports.FindAsync(id);
            if (leaveReport != null)
            {
                _context.LeaveReports.Remove(leaveReport);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LeaveReportExists(int id)
        {
            return _context.LeaveReports.Any(e => e.LeaveReportId == id);
        }
    }
}

LeaveReportApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="sv">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LeaveReportApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/LeaveReportApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LeaveReportApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Hem</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Anställda</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LeaveReports" asp-action="Index">Ledighetsrapporter</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - LeaveReportApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>